# Generated by Django 5.2.6 on 2025-12-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image_link',
            field=models.URLField(blank=True, help_text='Optional link to profile image if not uploading'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, help_text="Comma-separated skills/badges, e.g. 'Django, DRF Ready, SQA Mindset'", max_length=500),
        ),
    ]
