# Generated by Django 5.2.6 on 2025-12-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_profile_image_link_profile_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Site favicon (16x16 or 32x32 PNG)', null=True, upload_to='favicon/'),
        ),
    ]
