# Generated by Django 5.2.6 on 2025-12-31 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favicon_link',
            field=models.URLField(blank=True, help_text='Optional link to favicon if not uploading'),
        ),
    ]
