# Generated by Django 5.2.6 on 2025-12-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_profile_favicon_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favicon_link',
            field=models.CharField(blank=True, help_text='Optional link or path to favicon if not uploading', max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_link',
            field=models.CharField(blank=True, help_text='Optional link or path to profile image if not uploading', max_length=500),
        ),
    ]
