# Generated by Django 5.2.6 on 2025-12-31 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_profile_favicon_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Portfolio', help_text='Site title for browser tab', max_length=100)),
                ('primary_color', models.CharField(default='#b31919', help_text='Primary color (hex, e.g. #b31919)', max_length=7)),
                ('secondary_color', models.CharField(default='#333333', help_text='Secondary color (hex, e.g. #333333)', max_length=7)),
                ('accent_color', models.CharField(default='#ffffff', help_text='Accent color (hex, e.g. #ffffff)', max_length=7)),
                ('about_page_title', models.CharField(default='About Me', help_text='Title for About page', max_length=100)),
                ('about_page_subtitle', models.CharField(default='Get to know me better', help_text='Subtitle for About page', max_length=200)),
                ('experience_page_title', models.CharField(default='Experience', help_text='Title for Experience page', max_length=100)),
                ('projects_page_title', models.CharField(default='Projects', help_text='Title for Projects page', max_length=100)),
                ('contact_page_title', models.CharField(default='Contact', help_text='Title for Contact page', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
