# Generated by Django 5.2.6 on 2025-12-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_page_content',
            field=models.TextField(blank=True, help_text='Content for About page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_page_content',
            field=models.TextField(blank=True, help_text='Content for Contact page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='experience_page_content',
            field=models.TextField(blank=True, help_text='Content for Experience page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='projects_page_content',
            field=models.TextField(blank=True, help_text='Content for Projects page'),
        ),
    ]
