# Generated by Django 5.2.6 on 2026-01-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_sitesettings_about_page_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('dark_red', 'Dark Red (Default)'), ('dark_blue', 'Dark Blue'), ('dark_green', 'Dark Green'), ('dark_purple', 'Dark Purple'), ('light_red', 'Light Red'), ('light_blue', 'Light Blue'), ('light_green', 'Light Green'), ('light_purple', 'Light Purple'), ('cyberpunk', 'Cyberpunk'), ('minimal', 'Minimal')], default='dark_red', help_text='Choose a color theme for the entire site', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Tawfiq Hassan Nayem', help_text='Site title for browser tab', max_length=100),
        ),
    ]
