# Generated by Django 5.2.6 on 2026-01-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_sitesettings_theme_alter_sitesettings_site_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='theme',
            field=models.CharField(choices=[('dark_red', 'Dark Red (Professional)'), ('dark_blue', 'Dark Blue (Corporate)'), ('dark_green', 'Dark Green (Nature)'), ('dark_purple', 'Dark Purple (Creative)'), ('ocean_deep', 'Ocean Deep (Calm)'), ('sunset_orange', 'Sunset Orange (Warm)'), ('forest_dark', 'Forest Dark (Organic)'), ('royal_purple', 'Royal Purple (Elegant)'), ('cyberpunk', 'Cyberpunk (Futuristic)'), ('midnight_blue', 'Midnight Blue (Deep)')], default='dark_red', help_text='Choose a color theme for the entire site', max_length=20),
        ),
    ]
